name: Godot package

on: [push]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: cache-godot
        uses: actions/cache@v3
        env:
          cache-name: cache-godot
        with:
          path: ./cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          #cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scons
      - name: Download godot source code
        run: |
          choco install wget
          wget -c "https://downloads.tuxfamily.org/godotengine/4.0/beta16/godot-4.0-beta16.tar.xz" && 7z x -y *.xz && 7z x -y *.tar
      - name: mv
        if: runner.os == 'Windows'
        run: |
          mv custom.py $GITHUB_WORKSPACE/godot-4.0-beta16/custom.py
          mkdir $GITHUB_WORKSPACE/cache && $env:SCONS_CACHE="$GITHUB_WORKSPACE/cache"
          cd $GITHUB_WORKSPACE%/godot-4.0-beta16
          scons -Q platform=windows target=template_release arch=x86_64
