name: Godot package

on: [push]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-godot
        env:
          cache-name: godot-cache
        with:
          path: godot-cache/**
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('godot-cache/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('godot-cache/**') }}
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          #cache: 'pip'
      - name: Install Scons
        run: |
          python -m pip install --upgrade pip
          pip install scons
      - name: Download godot source code
        run: |
          choco install wget
          wget -c "https://downloads.tuxfamily.org/godotengine/4.0/beta16/godot-4.0-beta16.tar.xz" && 7z x -y *.xz && 7z x -y *.tar
      - name: Copy Files
        run: |
          mv custom.py $GITHUB_WORKSPACE/godot-4.0-beta16/
          ls $GITHUB_WORKSPACE/godot-4.0-beta16/
          mkdir godot-cache
          $env:SCONS_CACHE="$GITHUB_WORKSPACE\godot-cache"
          ls
          cd $GITHUB_WORKSPACE\godot-cache
      - name: Build
        run: |
          # scons -Q platform=windows target=template_release arch=x86_64
